version: "3.4"


services:
  calery_w:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    container_name: worker
    depends_on:
      - db
      - mongo
      - redis
      - rabbit
    volumes:
      - ./src:/src
    env_file:
      - ./envs/db_keys
      - ./envs/mongo_keys
      - ./envs/rabbit_keys
    links:
      - rabbit
    command : ["sh", "-c", "celery -A birthdays worker -P prefork -c 12 -l info"]
# solo - Сольный пул работает внутри рабочего процесса
# prefork - обойти глобальную блокировку интерпретатора python и юзать все ядра системы
# eventlet(задачи IO) и gevent - порождает потоки выполнения (необходимо в --concurreny указать колличество рабтников)
# -c - определяет колличество потоков/процессов
  jupyter:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    container_name: notebook 
    env_file:
      - ./envs/db_keys
      - ./envs/mongo_keys
      - ./envs/rabbit_keys
    ports:
      - "8888:8888"
    volumes:
      - ./src:/src
    depends_on:
      - db
      - redis
      - mongo
    command : ["sh", "-c", "jupyter notebook --allow-root --ip 0.0.0.0 --port 8888"]

  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - ./envs/db_keys
    volumes:
      - /psql_db/postgres_data:/var/lib/postgresql/data
      - /psql_db/postgres_data_backups:/backups

  adminer:
    image: adminer
    container_name: psql_admin
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongo_db
    env_file:
      - ./envs/mongo_keys

  mongo-express:
    image: mongo-express
    container_name: mongo_admin
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis:3.2-alpine
    container_name: redis_db
    volumes:
      - ./redis_data:/data

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitMQ
    env_file:
      - ./envs/rabbit_keys
    ports:
      - "15672:15672"
      - "5672:5672"
